
channels:
  - conda-forge
  - defaults
dependencies:
  - black=19
  - ipython=7.15
  - jupyter=1.0.0
  - jupyterlab=2.1
  - mkl=2020.1
  - numpy=1.18
  - pandas=1.0
  - psycopg2=2.8
  - pyprojroot=0.2
  - python=3.7
  - requests=2.24
  - pip:
    - pip
    - isort==4.3.21
    - python-dotenv==0.13
    - streamlit==0.61


